package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/Server.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from t:/workspace/open/src/java.corba/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Wednesday, June 27, 2018 at 6:54:24 PM Mountain Daylight Time
*/


/** Server callback API, passed to Activator in active method.
    */
public interface Server extends ServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Server
