package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/DISCARDING.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from t:/workspace/corba/src/java.corba/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Tuesday, December 19, 2017 6:16:17 PM PST
*/

public interface DISCARDING
{

  /** Object adapter state that causes all requests to be discarded.
   */
  public static final short value = (short)(2);
}
