package org.omg.Messaging;


/**
* org/omg/Messaging/SYNC_WITH_TRANSPORT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from t:/workspace/corba/src/java.corba/share/classes/org/omg/PortableInterceptor/Messaging.idl
* Tuesday, December 19, 2017 6:16:17 PM PST
*/

public interface SYNC_WITH_TRANSPORT
{

  /**
   * Constant, defined in the Messaging spec, to define how far the 
   * request shall progress before control is returned to the client.
   */
  public static final short value = (short)(1);
}
