package org.omg.IOP;


/**
* org/omg/IOP/TAG_POLICIES.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from t:/workspace/corba/src/java.corba/share/classes/org/omg/PortableInterceptor/IOP.idl
* Tuesday, December 19, 2017 6:16:16 PM PST
*/

public interface TAG_POLICIES
{

  /**
     * A profile component containing the sequence of QoS policies exported
     * with the object reference by an object adapter.
     */
  public static final int value = (int)(2L);
}
